variable "myip" {
  description = "The public IP address of your home network."
  default     = "0.0.0.0/0"
}

variable "aws_region" {
  description = "The AWS region where resources will be created."
  type        = string

  validation {
    condition     = length(var.aws_region) > 0
    error_message = "The aws_region variable must not be empty."
  }
}

variable "aws_availability_zone" {
  description = "The AWS availability zone within the specified region."
  type        = string

  validation {
    condition     = length(var.aws_availability_zone) > 0 && can(regex(var.aws_region, var.aws_availability_zone))
    error_message = "The aws_availability_zone variable must not be empty and must include the aws_region value."
  }
}

variable "aws_vpc_name" {
  description = "The name of the VPC."
  type        = string

  validation {
    condition     = length(var.aws_vpc_name) > 0
    error_message = "The aws_vpc_name variable must not be empty."
  }
}

variable "aws_ec2_sshkey_name" {
  description = "The name of the SSH key pair to use for EC2 instances."
  type        = string

  validation {
    condition     = length(var.aws_ec2_sshkey_name) > 0
    error_message = "The aws_ec2_sshkey_name variable must not be empty."
  }
}

variable "aws_instance_type" {
  description = "The EC2 instance type to use."
  type        = string
  default     = "c5d.xlarge"
}

variable "aws_spot_price" {
  description = "The maximum price to pay for EC2 spot instances."
  type        = string
  default     = "0.16"
}

variable "loglevel" {
  description = "The log level configuration for the Playpit platform."
  default     = ""
}

variable "user_name" {
  description = "The name of the student using the Playpit platform, in the format 'Firstname Lastname'."
  type        = string

  validation {
    condition     = can(regex("^[A-Z][a-z]+\\s[A-Z][a-z]+$", var.user_name))
    error_message = "The user_name must be in the format 'Firstname Lastname' with each name starting with an uppercase letter followed by lowercase letters."
  }
}

variable "basic_auth_password" {
  description = "The password for basic authentication. If unset, it will be generated by Terraform."
  type        = string
}

variable "domain_name" {
  description = "The domain name, e.g., if the FQDN is '57-58-59-60.somewhere.com', then the domain_name variable should be 'somewhere.com'. The '57-58-59-60' part will be derived from the VM public IP."
  type        = string
}

variable "training" {
  description = "The Playpit platform training configuration, must be either 'docker' or 'k8s'."
  type        = string

  validation {
    condition     = can(regex("^(docker|k8s)$", var.training))
    error_message = "Must be 'docker' or 'k8s'."
  }
}