variable "gcp_project" {
  description = "Google Cloud Platform (GCP) Project name"
  type        = string

  validation {
    condition     = length(var.gcp_project) > 0
    error_message = "The gcp_project variable must not be empty."
  }
}

variable "gcp_region" {
  description = "Google Cloud Platform (GCP) Region"
  type        = string

  validation {
    condition     = length(var.gcp_region) > 0
    error_message = "The gcp_region variable must not be empty."
  }
}

variable "gcp_zone" {
  description = "Google Cloud Platform (GCP) Zone"
  type        = string

  validation {
    condition     = length(var.gcp_zone) > 0 && can(regex(var.gcp_region, var.gcp_zone))
    error_message = "The gcp_zone variable must not be empty and must include the gcp_region value."
  }
}

variable "gcp_subnet_name" {
  description = "Subnet name. Provide name of existing subnet"
  type        = string

  validation {
    condition     = length(var.gcp_subnet_name) > 0
    error_message = "The gcp_subnet_name variable must not be empty."
  }
}

variable "domain_name" {
  description = "Domain name, for example: if FQDN is '57-58-59-60.somwhere.com', then domain_name variable should be like 'somewhere.com', and '57-58-59-60' will be picked from VM public IP automatically"
  type        = string
}

variable "gcp_instance_type" {
  description = "Instance type for provisioning"
  type        = string
  default     = "c2d-highcpu-4"
}

variable "loglevel" {
  description = "Playpit platform log level setting, magic variable for those in the know"
  default     = ""
}

variable "user_name" {
  description = "Playpit training participant name, approved by training owner"
  type        = string

  validation {
    condition     = can(regex("^[A-Z][a-z]+\\s[A-Z][a-z]+$", var.user_name))
    error_message = "The user_name must be in the format 'Firstname Lastname' with each name starting with an uppercase letter followed by lowercase letters."
  }
}

variable "basic_auth_password" {
  description = "Password for basic authentication. If unset, it will be generated by Terraform."
  type        = string
}

variable "training" {
  description = "Playpit platform training configuration"
  type        = string

  validation {
    condition     = can(regex("^(docker|k8s)$", var.training))
    error_message = "Must be 'docker' or 'k8s'."
  }
}